version: '3'
services:
    deploy:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./configs/dev/api_nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8086:80
