version: '3'
services:
    deploy:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - static-content:/var/www/
    nginx:
        image: docker.io/nginx:stable
        volumes:
            - static-content:/var/www/
            - ./configs/dev/api_nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80

volumes:
    static-content:
