version: '3'
services:
    dev:
        user: vscode
        build:
            context: .
            dockerfile: .devcontainer/dev.Dockerfile
            args:
                - USERNAME=vscode
                - USER_UID=1000
                - USER_GID=1000
                - WORK_DIR=/workspace
        volumes:
            - static-content:/workspace/public
            - .:/workspace
            - ~/.gitconfig:/etc/gitconfig:ro
    nginx:
        image: docker.io/nginx:stable
        volumes:
            - static-content:/var/www/:ro
            - ./configs/dev/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - 8085:80

volumes:
    static-content:
