version: '3'
services:
    dev:
        user: vscode
        environment:
            - USERNAME=vscode
            - USER_UID=1000
            - USER_GID=1000
        build:
            context: .
            dockerfile: .devcontainer/dev.Dockerfile
        volumes:
            - static-content:/workspace/public
            - .:/workspace:cached
            - ~/.gitconfig:/etc/gitconfig
