#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
PCO="$(dirname "$0")/../src/initts/ts/configs/project.js"
NVM_DIR="$HOME/.nvm"
NPM="[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && npm"

make actProd
git add "$PCO"

eval "$NPM" run-script build
eval "$NPM" run-script lint
